## PANDAS

In [ ]:
#Pandas is a Python library used to read, clean, organize, and analyze data. It is widely used in data analytics.
#Pandas will support two data structures: 1.series 2.data frame

In [1]:
%pip install pandas

Requirement already satisfied: pandas in .\miniconda3\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in .\miniconda3\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\miniconda3\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [8]:
import numpy as np

In [4]:
pd.__version__

'3.0.6'

## Creating series and dataframes

In [5]:
#pd.Series()-->One-dimensional data, like a single column
s=pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [12]:
#pd.Series()-->creates a 1D labeled array
s=pd.Series([10,20,30],index=['a','b','c'],name='values') 
s

a    10
b    20
c    30
Name: values, dtype: int64

In [4]:
#pd.DataFrame()-->from a dict of lists-creates a labeled 2D table
df=pd.DataFrame({'name':['Alice','Bob','Charlie','David'],
                 'age':[25,30,35,40],
                 'city':['NY','LA','SF','NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [9]:
#pd.DataFrame()-->creates a df from the list of dicts
pd.DataFrame([{'a':1,'b':2},{'a':3,'b':4}])

   a  b
0  1  2
1  3  4

In [10]:
#pd.DataFrame()-->from a Numpy array
pd.DataFrame(np.arange(6).reshape(2,3),columns=['x','y','z'])

   x  y  z
0  0  1  2
1  3  4  5

## Attributes and Inspection

In [11]:
#.shape-->(rows,cols)
df.shape

(4, 3)

In [12]:
#.columns-->column names
df.columns

Index(['name', 'age', 'city'], dtype='str')

In [13]:
#.index-->index range
df.index

RangeIndex(start=0, stop=4, step=1)

In [14]:
#data types
df.dtypes

name      str
age     int64
city      str
dtype: object

In [15]:
#values
df.values

array([['Alice', 25, 'NY'],
       ['Bob', 30, 'LA'],
       ['Charlie', 35, 'SF'],
       ['David', 40, 'NY']], dtype=object)

In [16]:
#total no.of elements
df.size

12

In [17]:
#.head()-->first n rows #default first 5 rows
df.head(3)

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF

In [18]:
#.tail()-->last n rows
df.tail(2)

      name  age city
2  Charlie   35   SF
3    David   40   NY

In [19]:
#summary of the df(dtypes,not null counts)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   city    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [20]:
#statistical summary
df.describe()

             age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

In [21]:
#memory usage by each column
df.memory_usage()

Index    132
name      32
age       32
city      32
dtype: int64

## Selection and Indexing (loc,iloc,at,iat)

In [22]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [23]:
# .set_index() ----> Set a column as the row index
df.set_index('name',inplace=False)

         age city
name
Alice     25   NY
Bob       30   LA
Charlie   35   SF
David     40   NY

In [24]:
df.set_index('name',inplace=True)

In [ ]:
#inplace=False --->this means changes are not stored or did permently
#inplace=true---->this means changes are stored and  did permently

In [5]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [26]:
df['age'] #column selection-single column returns

name
Alice      25
Bob        30
Charlie    35
David      40
Name: age, dtype: int64

In [6]:
df[['name','age']] #returns 2 columns

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [7]:
#.loc[] -->select a row by label
df.loc[0]

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [11]:
df.loc[0,'age'] #selects a scalar value by label(index,col name)

np.int64(25)

In [10]:
df.loc[3,'age']

np.int64(40)

In [13]:
df.loc[0:2,['name','age']] #displays 2 columns and 3 values

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [22]:
#select a row by integer position
df.iloc[0]

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [16]:
df.iloc[0,1] #select a scalar value by integer position

np.int64(25)

In [18]:
df.iloc[0:2,0:2] #select rows & col by int position

    name  age
0  Alice   25
1    Bob   30

In [20]:
df.at[0,'age'] #fast scalar access by label

np.int64(25)

In [21]:
df.iat[0,1] #fast scalar access by int position

np.int64(25)

## Filtering and boolean indexing

In [23]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [28]:
df[df['age']>28] #displays the values which are greater than 28

      name  age city
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [25]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [36]:
df[(df['age']>25)&(df['city']=='NY')] #multiple conditions combine with & and |

    name  age city
3  David   40   NY

In [32]:
df[(df['age']>25)&(df['age']<35)]

  name  age city
1  Bob   30   LA

In [34]:
df[(df['age']>35)|(df['city']=='NY')]

    name  age city
0  Alice   25   NY
3  David   40   NY

In [37]:
df[(df['name']=='Bob')|(df['city']=='NY')]

    name  age city
0  Alice   25   NY
1    Bob   30   LA
3  David   40   NY

In [39]:
#isin -->filters if the value is present in the table or not
df[df['city'].isin(['NY','LA'])]

    name  age city
0  Alice   25   NY
1    Bob   30   LA
3  David   40   NY

In [40]:
#.query-->filters using readable string expression
df.query('age>28 and city=="NY"')

    name  age city
3  David   40   NY

In [41]:
#.where-->keep matching values replace other with NaN
df.where(df['age']>28)

      name   age city
0      NaN   NaN  NaN
1      Bob  30.0   LA
2  Charlie  35.0   SF
3    David  40.0   NY

In [42]:
df.mask(df['age']>28)

    name   age city
0  Alice  25.0   NY
1    NaN   NaN  NaN
2    NaN   NaN  NaN
3    NaN   NaN  NaN

## Adding, modifying and dropping cols/rows

In [5]:
df2=df.copy()

In [10]:
df2

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [11]:
#adding a new column from an existing one
df2['senior']=df2['age']>30
df2

      name  age city  senior
0    Alice   25   NY   False
1      Bob   30   LA   False
2  Charlie   35   SF    True
3    David   40   NY    True

In [12]:
df2['age_plus_5']=df2['age']+5
df2

      name  age city  senior  age_plus_5
0    Alice   25   NY   False          30
1      Bob   30   LA   False          35
2  Charlie   35   SF    True          40
3    David   40   NY    True          45

In [13]:
df2.rename(columns={'city':'location'},inplace=True)
df2

      name  age location  senior  age_plus_5
0    Alice   25       NY   False          30
1      Bob   30       LA   False          35
2  Charlie   35       SF    True          40
3    David   40       NY    True          45

In [14]:
df2.drop(columns=['age_plus_5'],inplace=True) #dropping by col
df2

      name  age location  senior
0    Alice   25       NY   False
1      Bob   30       LA   False
2  Charlie   35       SF    True
3    David   40       NY    True

In [52]:
df2.drop(index=0,inplace=False) #dropping by rows

      name  age location  senior
1      Bob   30       LA      32
2  Charlie   35       SF      37
3    David   40       NY      42

In [15]:
df2.insert(1,'id',range(len(df2))) #insert a col at specific postion
df2

      name  id  age location  senior
0    Alice   0   25       NY   False
1      Bob   1   30       LA   False
2  Charlie   2   35       SF    True
3    David   3   40       NY    True

In [6]:
df2.assign(double_age=df2['age']*2)
df2

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

## Handling missing values

In [9]:
df_na=pd.DataFrame({'a':[1,np.nan,3],'b':[np.nan,2,3]})
df_na

     a    b
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0

In [10]:
#  .isna() ---> Boolean mask of missing values
df_na.isna()

       a      b
0  False   True
1   True  False
2  False  False

In [11]:
# .notna() ----> opposite of .isna()
df_na.notna()

       a      b
0   True  False
1  False   True
2   True   True

In [12]:
#df_na.isnull().sum() ---> Count of missing values per columns
df_na.isnull().sum()

a    1
b    1
dtype: int64

In [13]:
# .dropna()-----> Drop rows containing any NaN
df_na.dropna()

     a    b
2  3.0  3.0

In [14]:
# .dropna(axis=1)-----> Drop columns containing any NaN
df_na.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [15]:
#  .fillna() ---->  fill missing values with constant
df_na.fillna(0)

     a    b
0  1.0  0.0
1  0.0  2.0
2  3.0  3.0

In [16]:
#   .ffill() -----> Forward fill missing values
df_na.ffill()

     a    b
0  1.0  NaN
1  1.0  2.0
2  3.0  3.0

In [17]:
#   .bfill() -----> Backward fill missing values
df_na.bfill()

     a    b
0  1.0  2.0
1  3.0  2.0
2  3.0  3.0

## Sorting And Ranking

In [18]:
df=pd.DataFrame({
    'name':['Alice','Bob','Charlie','David'],
    'age':[25,30,35,40],
    'city':['NY','LA','SF','NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [19]:
# .sort_values() ----> Arrange the values in ascending order
df.sort_values('age')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [20]:
df.sort_values(['city','age'],ascending=[True,False])

      name  age city
1      Bob   30   LA
3    David   40   NY
0    Alice   25   NY
2  Charlie   35   SF

In [21]:
# .sort_index() ----> Sort rows by the index
df.sort_index()

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [22]:
# .rank() ----> Rank values within a column
df['age'].rank

<bound method NDFrame.rank of 0    25
1    30
2    35
3    40
Name: age, dtype: int64>

In [23]:
# .nlargest() ----> Top n rows by a column
df.nlargest(2,'age')

      name  age city
3    David   40   NY
2  Charlie   35   SF

In [24]:
# .nsmallest()----> Bottom n rows by a column
df.nsmallest(3,'age')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF

## Aggregation and Statistics

In [25]:
# .sum() / .mean() / .median() ------> Basic Aggregations
df['age'].sum(), df['age'].mean(), df['age'].median()

(np.int64(130), np.float64(32.5), np.float64(32.5))

In [26]:
# .std() / .var() ----> Spread of data
df['age'].std(), df['age'].var()

(np.float64(6.454972243679028), np.float64(41.666666666666664))

In [27]:
# .min() / .max() ----> Smallest and Largest value
df['age'].min(), df['age'].max()

(np.int64(25), np.int64(40))

In [28]:
# .count() ---> Number of not null values
df['age'].count()

np.int64(4)

In [29]:
# .agg()----> Apply a multiple aggregation functions at once
df.agg({'age':['mean','max','min']})

       age
mean  32.5
max   40.0
min   25.0

In [30]:
# .corr() ----->correlation matrix of numeric columns
df.corr(numeric_only=True)

     age
age  1.0

In [31]:
# .mode() ---->Most frequently occuring value
df['city'].mode()

0    NY
Name: city, dtype: str

## GroupBy Operations

In [37]:
g=df.groupby('city')

In [38]:
#  .size()---> Number of rows in each group
g.size()

city
LA    1
NY    2
SF    1
dtype: int64

In [40]:
# .agg()---> On a group by -- Multiple aggregations per group

In [41]:
g.agg({'age':['mean','sum']})

       age
      mean sum
city
LA    30.0  30
NY    32.5  65
SF    35.0  35

In [42]:
#  .apply()---> on a groupby -- custom function per group
g.apply(lambda x: x['age'].max() - x['age'].min())

city
LA     0
NY    15
SF     0
dtype: int64

In [43]:
add=lambda a,b:a+b

In [44]:
add(2,2)

4

In [ ]:
Iterating over groups with a for loop

In [45]:
for name, group in g:
    print(name)
    print(group)

LA
  name  age city
1  Bob   30   LA
NY
    name  age city
0  Alice   25   NY
3  David   40   NY
SF
      name  age city
2  Charlie   35   SF

In [46]:
# .get_group() ---> Retrieve a specific group
g.get_group('NY')

    name  age city
0  Alice   25   NY
3  David   40   NY

In [47]:
#Data
type(df)

pandas.DataFrame

In [50]:
#Converting the file from pandas into csv
df.to_csv('data.csv', index=False)

In [51]:
# to import the file 
pd.read_csv('data.csv')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [ ]:
#Converting the file  into json

In [ ]:
# .to_json() / pd.read_json() ----> write and read json files

In [52]:
df.to_json('data.json', orient='records')
pd.read_json('data.json')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [ ]:
# .to_excel() / pd.read_excel() ---> Write and read excel files

In [53]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [54]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [55]:
df.to_excel('data.xlsx',index=False)
pd.read_excel('data.xlsx')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [ ]:
# .to_dict()---> Convert dataframe into a list of dictionary

In [56]:
df.to_dict(orient='records')

[{'name': 'Alice', 'age': 25, 'city': 'NY'},
 {'name': 'Bob', 'age': 30, 'city': 'LA'},
 {'name': 'Charlie', 'age': 35, 'city': 'SF'},
 {'name': 'David', 'age': 40, 'city': 'NY'}]

In [57]:
pd.DataFrame.from_dict({'a':[1,2]})

   a
0  1
1  2